
# Appendix C - Defining Sets {-}

## Defining Sets {-}

After all existing data and knowledge are collated for known and modelled crossings, an iterative ranking process is conducted to help confirm barriers to target for rehabilitation to meet the goals. The ranking process is primarily used to guide field assessments and maximize efficiency in ground truthing data/knowledge inputs and model outputs, while providing a secondary purpose to evaluate the relative key habitat gains of confirmed barriers in the watershed. Field assessments can include an assessment of either the passability status of a structure (whether fish can pass upstream, and to what degree), whether the upstream habitat is suitable for the focal species, and whether there are other undocumented human-made or natural barriers upstream or downstream. First, structures are grouped into ‘sets’. Sets are identified by maximizing the key habitat gain for barriers in the same tributary system. If adding a structure to a set reduces the gain-per-barrier (i.e., the total habitat gain of the set divided by the number of barriers in the set), then it is excluded and will be considered part of another set. This results in sets ranging from one to five structures. Then, each set is ranked by its potential to contribute to restoring the overall habitat connectivity. The higher a set is ranked, the more potential contribution it makes to restoring the overall habitat connectivity, therefore making the set a higher priority for field assessment. By assessing the passability status and upstream habitat of the top-ranked sets, we close knowledge gaps with the greatest influence on the overall connectivity model results.

Sets are ranked by a combination of two factors:

1.	The long-term potential impact that restoring connectivity at that structure could have on the overall connectivity status. This was measured by calculating and ranking sets by the amount of total upstream key habitat (i.e., ignoring any additional upstream sets). This ranking identifies sets that would have the greatest long-term potential gain in habitat connectivity once any subsequent upstream barriers are addressed.

2.	The immediate potential impact that restoring connectivity at that structure could have on the overall connectivity status. This was measured by calculating the amount of functional upstream habitat (i.e., key habitat between that set and the next upstream set of structures). Sets were then ranked by functional upstream habitat amount in tiers, where sets with no downstream sets were ranked first, then sets with one downstream set, and so on. This ranking identifies sets that have the greatest immediate potential gain in habitat by prioritizing sets that don’t rely on rehabilitation of downstream or upstream sets to realize these gains.

An overall ranking for each set was produced as a composite of the long-term and immediate potential gain ranks to prioritize sets that maximize long-term and immediate potential to improve key habitat connectivity in the watershed. All structures in the watershed (excluding those confirmed as passable) were ranked and a subset of those structures were selected by the planning team to assess in the 2023 field season.

Each structure has a “gain per structure” value associated with it, which is a measure of the linear length of key habitat upstream until the next structure. Grouping structures into sets starts by taking the most downstream structure (e.g., structure A) in the stream and the next structure immediately upstream of it (e.g., structure B) and calculates the average gain per structure in that set (structure A+B/2). This process is repeated with sets increasing from two structures to five structures (e.g., structure A+B+C+D+E/5). The set with the highest average gain per structure is grouped together. Structures are left as individuals if adding a second structure reduces the average gain per structure (e.g., structure A > structure A+B/2). After this set is grouped, the algorithm moves to the next structure upstream of the set and repeats the process iteratively until all structures in the stream are in a set and the entire process repeats for each stream in the network.

## Automatic Barrier Ranking Process{-}

### Overview of Barrier Ranking 

| Parameter  | Criteria  |
|--------|--------|
| Set  | Barriers that are located on the same stream are grouped together. After they are grouped together, the average length of habitat gain (kms) per barrier removal is calculated.  |
| Ranked Structure List   | A **ranked structure list** orders structures by amount of habitat blocked, and where removal of an individual structure or a group of structures (a **“set”**) is more effective in opening up habitat.    |

: {.striped .hover}

A **ranked structure list** helps determine where structures are blocking large amounts of habitat, and where removal of an individual structure or a group of structures (a “**set**”) is more effective in opening up habitat, by ranking structures based on amount of habitat blocked. This list communicates to biologists and partners which barriers are the most effective to address in terms of increasing accessible habitat — useful for biologist field work planning — and to compare with a partner’s own understanding own priorities when determining the most important barriers for remediation. This considers a combination of  immediate and long-term habitat gains for removal. 

During a FishPass model re-run,  the script rank_barriers.py ranks barriers in a watershed for a given species in order of which barriers or barrier sets, when removed, would open up the best habitat upstream based on a balance of immediate and long-term habitat gains. It should be noted that this script does not rank passable barriers or barriers which do not block any upstream habitat.

These sets are then ranked along the same stream whose removal as a group would open up more kms of habitat than any of those structures on their own. Those sets that would have a higher average gain per barrier removal would be ranked higher than others. 

### Ranking Barrier Sets

Barrier sets are ranked based on a combination of immediate and long term habitat gains from removal. 

First the barrier sets are sorted by number of barriers downstream of the set then by average gain per barrier. This creates a list where sets with zero downstream barriers are ranked by average gain per barrier first, then sets with 1 downstream barrier, then 2, etc. There is a cutoff of habitat gains less than 500m. Such barrier sets are moved to the bottom of the entire list. 

The barrier sets are given a rank according to this sorting giving a ranking based on immediate habitat gains from barrier set removal. In the final output, this is the column called rank_avg-gain_tiered.

Barrier sets are separately ranked based on total upstream habitat from the set including all habitat blocked by other barrier sets upstream. This gives a ranking based on long term habitat gains from barrier set removal.

The immediate rank and the long term rank is then added together and the list of barrier sets is sorted by this value from lowest to highest. Then the barrier sets are re-ranked according to this combined value. This combined ranking favours sets with good immediate and long term habitat gains.

This combined ranking is also offered in a tiered format where barriers receive a letter grade where A is the top 10, B is 11-20, C is 21-30, and D is for all others. 

